hass/xiaomi_miot: Add homekit to services.home-assistant.extraComponents
Needed after commit 7a26f9a1, or:

```
  File "/nix/store/...-homeassistant-2024.11.1/lib/python3.12/site-packages/homeassistant/components/homekit/__init__.py", line 16, in <module>
    from pyhap import util as pyhap_util
ModuleNotFoundError: No module named 'pyhap'
```